### ISSUE TITLE
PHP 8.1 Compatibility

### ISSUE THREAD

**Issue by bashgeek** [filegator/filegator#295] opened 2022-01-13 03:29 UTC
I ran into some issues running Filegator on PHP 8.1. First of all, most of the functionality works, but the upload does not anymore, getting the following error in the logs:

`[13-Jan-2022 03:07:39 UTC] PHP Fatal error:  Uncaught Error: Call to a member function isValid() on array in /X/backend/Controllers/UploadController.php:70`

Couldn't test further than this, probably has to do with the compatibility of Symfony 4.4 and PHP 8.1 and different behaviour, the `$request->files->get('filename')` method seem to return the `$_FILES[filename]` values instead of a `UploadedFile` object.

**Comment by alcalbg** [comment] 2022-01-13 10:22
Confirmed!

Thank you, this will be fixed soon.

**Closed** 2022-01-13 10:25 UTC

**Comment by alcalbg** [comment] 2022-01-13 10:54
It turns out, they already fixed this in Symfony with https://github.com/symfony/symfony/pull/42112 :)

**Comment by bashgeek** [comment] 2022-01-13 12:52
Ah, so it would just need a composer update then :-)

Anyway, working now, thanks!
